### ISSUE TITLE
同学，有木有其他直播平台的API？

### ISSUE THREAD

**Issue by liwenDeng** [ShaneXie/DouyuTv-Chatroom-Electron#4]
我是做iOS客户端开发的，想写个直播APP练手，目前找到有[PANDATV](https://github.com/liwenDeng/pandatvAPI)的API和你的斗鱼API，我想问下你那有木有其他平台的API呀？求分享

**Comment by axe-me** [comment]
@liwenDeng 暂时没有。不过你可以自己抓一下。。
